name: ailoitte_components
description: A new Flutter package project.
version: 0.0.1
# homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  intl:
  # Bloc for state management
  flutter_bloc: ^8.1.1
  # Value equality
  equatable: ^2.0.5
  # Local Cache
  shared_preferences: ^2.0.15
  loading_animation_widget: ^1.2.0+4
  # Cached Network Image
  cached_network_image: ^3.2.2
  # Dio
  dio: ^5.0.3
  # For handling toast messages
  fluttertoast: ^8.0.9
  dropdown_button2: ^2.1.4
#  dropdown_textfield: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.3.0

flutter:

assets:
  - assets/
