// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1OW4Hw-_0ik7lLg84WNNEwjzTqGUS8Zs',
    appId: '1:301342070628:web:43793cd7ee6279bb490c71',
    messagingSenderId: '301342070628',
    projectId: 'mysutra-da737',
    authDomain: 'mysutra-da737.firebaseapp.com',
    storageBucket: 'mysutra-da737.appspot.com',
    measurementId: 'G-HPY7S1FQPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWp-3cZXqsOnpZCVRnHZkvc5K6sA-2ao',
    appId: '1:301342070628:android:b606cc7bf06f32cd490c71',
    messagingSenderId: '301342070628',
    projectId: 'mysutra-da737',
    storageBucket: 'mysutra-da737.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnLoJRY0YeKip-j-NH-0vMo28JiBYGR6c',
    appId: '1:301342070628:ios:7068652c3b3fe62f490c71',
    messagingSenderId: '301342070628',
    projectId: 'mysutra-da737',
    storageBucket: 'mysutra-da737.appspot.com',
    iosBundleId: 'com.example.mySutra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3R1gg4VcfcpnsHuM0ZE52M49byzK5U00',
    appId: '1:985473802548:ios:5a8f3d870b31ce66c40561',
    messagingSenderId: '985473802548',
    projectId: 'mysutra-2c963',
    storageBucket: 'mysutra-2c963.appspot.com',
    iosBundleId: 'com.example.mySutra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu_F63iUt-9g-lg5UMrzfpEGddAU2Dp1w',
    appId: '1:985473802548:web:291872761318e855c40561',
    messagingSenderId: '985473802548',
    projectId: 'mysutra-2c963',
    authDomain: 'mysutra-2c963.firebaseapp.com',
    storageBucket: 'mysutra-2c963.appspot.com',
    measurementId: 'G-JMFC2MGSGQ',
  );
}